Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/bionic64"
	
	config.vm.define :ci do |ci_config|
		ci_config.vm.network "private_network", ip: "192.168.50.10"

		ci_config.vm.provision "ansible" do |ansible|
			ansible.playbook = "playbooks/ci.yml"
		end
	end

	config.vm.define :db do |db_config|
		db_config.vm.network "private_network", ip: "192.168.50.11"

		db_config.vm.provision "ansible" do |ansible|
			ansible.playbook = "playbooks/db.yml"
		end
	end
	
	config.vm.define :web_a do |web_config|
		web_config.vm.network "private_network", ip: "192.168.50.12"

		web_config.vm.provision "ansible" do |ansible|
			ansible.playbook = "playbooks/web.yml"
		end
	end

	# config.vm.define :web_b do |web_config|
	# 	web_config.vm.network "private_network", ip: "192.168.50.13"

	# 	web_config.vm.provision "ansible" do |ansible|
	# 		ansible.playbook = "playbooks/web.yml"
	# 	end
	# end

	# config.vm.define :lb do |lb_config|
	# 	lb_config.vm.network "private_network", ip: "192.168.50.15"

	# 	lb_config.vm.provision "ansible" do |ansible|
	# 		ansible.playbook = "playbooks/lb.yml"
	# 	end
	# end
end